// Resume Generation Service

import API from './api.js';
import Utils from './utils.js';

class ResumeService {
    async downloadPDF() {
        try {
            Utils.showLoading('downloadBtn', 'Generating PDF...');
            await API.downloadResume();
            Utils.showToast('✅ Resume downloaded successfully!', 'success');
            return { success: true };
        } catch (error) {
            console.error('Failed to download PDF:', error);
            Utils.showToast('❌ Failed to download resume', 'error');
            return { success: false, error: error.message };
        } finally {
            Utils.hideLoading('downloadBtn');
        }
    }

    async getTextResume() {
        try {
            const data = await API.getTextResume();
            return { success: true, text: data.resumeText };
        } catch (error) {
            console.error('Failed to get text resume:', error);
            return { success: false, error: error.message };
        }
    }

    downloadTextResume(resumeText, fileName = 'resume.txt') {
        Utils.downloadFile(resumeText, fileName, 'text/plain');
        Utils.showToast('✅ Text resume downloaded!', 'success');
    }

    formatResumeText(profile, user) {
        const personal = profile.personalInfo || {};
        const skills = profile.skills || [];
        const experience = profile.experience || [];
        const projects = profile.projects || [];

        return `
╔═══════════════════════════════════════════════════════════════╗
║                    ${user.name || 'Candidate Profile'.padEnd(50)}                    ║
╚═══════════════════════════════════════════════════════════════╝

📧 ${personal.email || user.email || 'Not provided'}     
📞 ${personal.phone || 'Not provided'}     
📍 ${personal.location || 'Not provided'}

═══════════════════════════════════════════════════════════════
✨ PROFESSIONAL SUMMARY
═══════════════════════════════════════════════════════════════
${profile.aiGenerated?.summary || 'No summary available'}

═══════════════════════════════════════════════════════════════
🛠️ TECHNICAL SKILLS
═══════════════════════════════════════════════════════════════
${skills.map(s => s.name || s).join(' • ') || 'No skills added'}

═══════════════════════════════════════════════════════════════
💼 WORK EXPERIENCE
═══════════════════════════════════════════════════════════════
${experience.map(exp => `
📌 ${exp.role} at ${exp.company}
   ${exp.startDate || ''} - ${exp.current ? 'Present' : (exp.endDate || '')}
   ${exp.description || 'No description provided'}
`).join('\n') || 'No experience added'}

═══════════════════════════════════════════════════════════════
🚀 PROJECTS
═══════════════════════════════════════════════════════════════
${projects.map(proj => `
📁 ${proj.title}
   Tech: ${proj.techStack || 'Not specified'}
   ${proj.description || 'No description provided'}
`).join('\n') || 'No projects added'}

═══════════════════════════════════════════════════════════════
Generated by TalentAI - AI-Powered Recruitment Platform
Profile ID: ${user.profileId || 'N/A'}
Generated: ${new Date().toLocaleString()}
═══════════════════════════════════════════════════════════════
        `;
    }

    // Share profile on LinkedIn
    shareOnLinkedIn(profileUrl) {
        const url = encodeURIComponent(profileUrl);
        const text = encodeURIComponent("Check out my AI-powered professional profile on TalentAI! 🚀");
        window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${url}&summary=${text}`, '_blank');
        Utils.showToast('Opening LinkedIn...', 'info');
    }

    // Share profile on Twitter
    shareOnTwitter(profileUrl, profileName) {
        const url = encodeURIComponent(profileUrl);
        const text = encodeURIComponent(`Check out my AI-powered profile on TalentAI! I'm ${profileName} and I'm looking for new opportunities. 🚀`);
        window.open(`https://twitter.com/intent/tweet?text=${text}&url=${url}`, '_blank');
        Utils.showToast('Opening Twitter...', 'info');
    }
}

export default new ResumeService();