const express = require('express');
const auth = require('../middleware/auth');
const Profile = require('../models/Profile');
const User = require('../models/User');
const PDFService = require('../services/pdfService');

const router = express.Router();

// Download resume as PDF
router.get('/download', auth, async (req, res) => {
    try {
        const user = await User.findById(req.userId);
        const profile = await Profile.findOne({ user: req.userId });
        
        if (!profile) {
            return res.status(404).json({ error: 'Profile not found' });
        }
        
        const pdfBuffer = await PDFService.generateResume(profile, user);
        
        user.resumeDownloads = (user.resumeDownloads || 0) + 1;
        await user.save();
        
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=${user.name || 'resume'}_talentai.pdf`);
        res.send(pdfBuffer);
    } catch (error) {
        console.error('Download resume error:', error);
        res.status(500).json({ error: error.message });
    }
});

// Generate text resume
router.post('/generate-text', auth, async (req, res) => {
    try {
        const user = await User.findById(req.userId);
        const profile = await Profile.findOne({ user: req.userId });
        
        if (!profile) {
            return res.status(404).json({ error: 'Profile not found' });
        }
        
        const resumeText = `
═══════════════════════════════════════════════════════════════
                    ${user.name || 'Candidate Profile'}                        
═══════════════════════════════════════════════════════════════

📧 ${profile.personalInfo?.email || user.email || 'Not provided'}     
📞 ${profile.personalInfo?.phone || 'Not provided'}     
📍 ${profile.personalInfo?.location || 'Not provided'}

═══════════════════════════════════════════════════════════════
✨ PROFESSIONAL SUMMARY
═══════════════════════════════════════════════════════════════
${profile.aiGenerated?.summary || 'No summary available'}

═══════════════════════════════════════════════════════════════
🛠️ TECHNICAL SKILLS
═══════════════════════════════════════════════════════════════
${(profile.skills || []).map(s => s.name).join(' • ') || 'No skills added'}

═══════════════════════════════════════════════════════════════
💼 WORK EXPERIENCE
═══════════════════════════════════════════════════════════════
${(profile.experience || []).map(exp => `
${exp.role} at ${exp.company}
${exp.startDate || ''} - ${exp.current ? 'Present' : (exp.endDate || '')}
${exp.description}
`).join('\n') || 'No experience added'}

═══════════════════════════════════════════════════════════════
🚀 PROJECTS
═══════════════════════════════════════════════════════════════
${(profile.projects || []).map(proj => `
${proj.title}
Tech Stack: ${proj.techStack}
${proj.description}
`).join('\n') || 'No projects added'}

═══════════════════════════════════════════════════════════════
Generated by TalentAI - AI-Powered Recruitment Platform
Profile ID: ${user.profileId}
Generated: ${new Date().toLocaleString()}
═══════════════════════════════════════════════════════════════
        `;
        
        res.json({ success: true, resumeText });
    } catch (error) {
        console.error('Generate text resume error:', error);
        res.status(500).json({ error: error.message });
    }
});

module.exports = router;